### PR TITLE
NETOBSERV-1678: allow agent image configuration

### PR DESCRIPTION
**Pull request by jpinsonneau**
## Description

- Configure agent image at build time using `AGENT_IMAGE` param

```
$ USER=netobserv VERSION=main AGENT_IMAGE=quay.io/netobserv/netobserv-ebpf-agent:release-1.6 make oc-commands 
### Generating oc commands
DIST_DIR=build \
K8S_CLI_BIN=oc \
IMAGE=quay.io/netobserv/network-observability-cli:main \
PULL_POLICY=Always \
AGENT_IMAGE=quay.io/netobserv/netobserv-ebpf-agent:release-1.6 \
VERSION=main \
./scripts/inject.sh
updating CLI images to quay.io/netobserv/network-observability-cli:main
updating CLI version to main
updating CLI pull policy to Always
updating eBPF agent images to quay.io/netobserv/netobserv-ebpf-agent:release-1.6
updating K8S CLI to oc
prefixing with oc-
pull policy not provided, keeping current ones
output generated in build folder
```

- Override agent image at run time using `NETOBSERV_AGENT_IMAGE` environment variable
```
$ NETOBSERV_AGENT_IMAGE=quay.io/netobserv/netobserv-ebpf-agent:release-1.6 ./build/oc-netobserv flows
```

Both will result in custom eBPF agent image set as:
```
$ oc describe pod netobserv-cli-chz4p -n netobserv-cli
Name:             netobserv-cli-chz4p
Namespace:        netobserv-cli
Containers:
  netobserv-cli:
    Image:          quay.io/netobserv/netobserv-ebpf-agent:release-1.6
...
```

## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [X] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [X] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Review by OlivierCazade — APPROVED** [review]
LGTM

Side note, I think this yaml approach will be hard to maintain if we keep adding feature here. Encryption and authentication of the connection between ebpf and cli container come to my mind.

**Comment by Amoghrd** [comment]
This can be merged, I will test it downstream

**Comment by jpinsonneau** [comment]
> LGTM
> 
> Side note, I think this yaml approach will be hard to maintain if we keep adding feature here. Encryption and authentication of the connection between ebpf and cli container come to my mind.

That's right ! We can improve using a function or yq as the filters does in a next PR.
Let's just unlock the QA for now

**Pull request merged**
