### PR TITLE
NETOBSERV-1703 Add enrichment in packet capture

### PR DESCRIPTION
**Pull request by jpinsonneau**
## Description

CLI pcap showing table while running packet capture:
- as same as flow you can live filter on these 
- and see enrichement

Output file is a `pcapng` including Src / Dst enriched fields (currently using frame -> Interface section)
Other fields are not kept here since the packet is supposed to contains everything but we can add extras if needed

image
image

## Dependencies

https://github.com/netobserv/netobserv-ebpf-agent/pull/364

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [X] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [X] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by jpinsonneau** [comment]
e2e will pass as soon as eBPF PR is merged

**Comment by jpinsonneau** [comment]
Rebased to include latests options.

You can give a try with ebpf image using:
```
NETOBSERV_AGENT_IMAGE=quay.io/netobserv/netobserv-ebpf-agent:30c0f75 ./build/oc-netobserv packets
```

**Comment by jpinsonneau** [comment]
Rebased without changes

**Review by jotak — APPROVED** [review]

**Pull request merged**
