### PR TITLE
NETOBSERV-1623 update sed commands to support macos

### PR DESCRIPTION
**Pull request by jpinsonneau**
## Description

Attempt to make `sed` working on MacOs.

Run the following target to give a try:
```bash
$ make oc-commands 
### Generating oc commands
DIST_DIR=build \
K8S_CLI_BIN=oc \
IMAGE=quay.io/julien/network-observability-cli:main \
PULL_POLICY=Always \
VERSION=main \
./scripts/inject.sh
updating CLI images to quay.io/julien/network-observability-cli:main
updating CLI pull policy to Always
updating CLI version to main
updating K8S CLI to oc
prefixing with oc-
pull policy not provided, keeping current ones
output generated in build folder
```

The generated file `./build/oc-netobserv` should contains YAMLs and your quay image with version main.

## Dependencies

n/a

## Checklist

If you are not familiar with our processes or don't know what to answer in the list below, let us know in a comment: the maintainers will take care of that.

* [x] Is this PR backed with a JIRA ticket? If so, make sure it is written as a title prefix _(in general, PRs affecting the NetObserv/Network Observability product should be backed with a JIRA ticket - especially if they bring user facing changes)._
* [ ] Does this PR require product documentation?
  * [ ] If so, make sure the JIRA epic is labelled with "documentation" and provides a description relevant for doc writers, such as use cases or scenarios. Any required step to activate or configure the feature should be documented there, such as new CRD knobs.
* [ ] Does this PR require a product release notes entry?
  * [ ] If so, fill in "Release Note Text" in the JIRA.
* [ ] Is there anything else the QE team should know before testing? E.g: configuration changes, environment setup, etc.
  * [ ] If so, make sure it is described in the JIRA ticket.
* QE requirements (check 1 from the list):
  * [x] Standard QE validation, with pre-merge tests unless stated otherwise.
  * [ ] Regression tests only (e.g. refactoring with no user-facing change).
  * [ ] No QE (e.g. trivial change with high reviewer's confidence, or per agreement with the QE team).

### CODE REVIEW

**Comment by jpinsonneau** [comment]
@Amoghrd could you please give another try with these changes ? 
I don't see why it would not work according to what I read from https://stackoverflow.com/a/4247319

**Comment by jpinsonneau** [comment]
Thanks @stleerh for the details ! Do you run on Mac too ?

Let's give a try with first solution as I already try `gsed` and it was more complex to manage.
The inject script works in a `tmp` folder and already cleanup before copying to output so it's not a problem to me to have temporary `.bak` files in between.

**Comment by stleerh** [comment]
FYI, commit 3 is my change in this pull request.

**Comment by Amoghrd** [comment]
@stleerh latest commits works fine on mac.
/label qe-approved

**Comment by jpinsonneau** [comment]
Thanks for the help @stleerh & @Amoghrd !

**Pull request merged**
